### ISSUE TITLE
Bad lighting and shadowing when the sun's direction is at a specific angle.

### ISSUE THREAD

**Issue by L1uyu** [Global-Illuminati/Precomputed-Light-Field-Probes#2]
Thanks for your sharing. It's great to see an implementation for Webgl GI. That's also my interest, so I tried your demo.
Unfortunately, I found some bugs there. When the sun lights a plane(nearly vertical), the plane can't get the proper lighting. You can see the pic below.
![E$ J(FE1O5HHMI9GA}8R_OS](https://user-images.githubusercontent.com/41277740/188305056-dfcf70a0-88c3-4fd4-9917-a5cd8373ffb5.jpg)
![image](https://user-images.githubusercontent.com/41277740/188305076-9fd2d8e0-210d-4047-9298-c5ffbf916fac.png)
Is there anything I miss? Hope for your reply.

**Comment by DanielHesslow** [comment]
Hi, thanks for your interest, 

This was part of our master thesis work 4 years ago, bugs are expected and wont be fixed. Feel free to fork the repo if you want to improve it.

Daniel
